api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        jsonhal:
            mime_types:
                - application/hal+json
        jsonapi:
            mime_types:
                - application/vnd.api+json
        xml:
            mime_types:
                - application/xml
                - text/xml
        yaml:
            mime_types:
                - application/x-yaml
